//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExplorer_MichalRac.MVVM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileExplorer_MichalRac.MVVM.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory to open.
        /// </summary>
        public static string File_Browser_Description {
            get {
                return ResourceManager.GetString("File_Browser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory.
        /// </summary>
        public static string Open_Directory {
            get {
                return ResourceManager.GetString("Open_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string Open_File {
            get {
                return ResourceManager.GetString("Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Sort_Ascending {
            get {
                return ResourceManager.GetString("Sort_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By extension.
        /// </summary>
        public static string Sort_By_Extension {
            get {
                return ResourceManager.GetString("Sort_By_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By modify date.
        /// </summary>
        public static string Sort_By_Modify_Date {
            get {
                return ResourceManager.GetString("Sort_By_Modify_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name.
        /// </summary>
        public static string Sort_By_Name {
            get {
                return ResourceManager.GetString("Sort_By_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By size.
        /// </summary>
        public static string Sort_By_Size {
            get {
                return ResourceManager.GetString("Sort_By_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Sort_Descending {
            get {
                return ResourceManager.GetString("Sort_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort settings.
        /// </summary>
        public static string Sort_Dialog_Description {
            get {
                return ResourceManager.GetString("Sort_Dialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting directory: .
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
    }
}
